name: gcloud_flutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  cupertino_icons:
  gcloud:
  googleapis_auth:
  image_picker:
  mime:
  path_provider:

  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  assets: 
    - assets/credentials.json
  uses-material-design: true
